### ISSUE TITLE
PWA?

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/so-cards#11]
Is it possible to turn this into a Progressive web application? 

This would allow users to add the web URL to home screen. 

https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps/Add_to_home_screen

**Comment by fk00750** [comment]
@yes it is possible, and it can be done easily with the help of lighthouse

**Comment by bacloud22** [comment]
Cool stuff @fk00750 

Can you try that on a second branch?

**Comment by fk00750** [comment]
@bacloud22  Yeah I would love to make it a PWA.

**Comment by fk00750** [comment]
can you assign me this issue

**Comment by bacloud22** [comment]
Ofc let's do it ! Good luck 🤞

**Comment by bacloud22** [comment]
Hum if you really know about SEO, and without deteriorating functionalities or design, then go for it.

**Comment by bacloud22** [comment]
very cool stuff. 
Unfortunately, fontawesome icons do not load now !
Could you please fix that ?

**Comment by bacloud22** [comment]
Why is this ?
https://github.com/bacloud22/so-cards/blob/c3a1929e110ba61d5e97d19fe14b702636bb84b4/index.html#L36
in both html files.
thanks

**Comment by bacloud22** [comment]
![Capture](https://user-images.githubusercontent.com/10267332/184837906-fb01e78c-45fb-4fbb-9646-f25977ce84e4.PNG)

**Comment by fk00750** [comment]
@bacloud22 this error is due to the meta tag of content security policy

**Comment by fk00750** [comment]
@bacloud22  i am working on it

**Comment by bacloud22** [comment]
fixed https://github.com/bacloud22/so-cards/commit/ccdad15f6a78a27c7b8e63dce05a4da3a21df7e4
Thanks @fk00750

**Comment by bacloud22** [comment]
If
