### ISSUE TITLE
Links to social media accounts

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/so-cards#12]
Turn values to links to their respective websites, so that a visitor go straight to the author accounts.
Check[ this for example](https://so-c.me/card.html#bXktYWxpYXMsc2ludmZkc3RhLHV0b3ZmZG9iLHd0Zi1hY2Vib29rLHR3YXR0ZXIsc25hdGNoY2hhdCxnZW1haWxAZ21haWwuY29tLDA3Nzg2ODA4Mjc=@-1977975060%2)

https://github.com/bacloud14/so-cards/blob/f0e40f664a9497ddd4793046cac10c747196ce3f/card.js#L79

**Comment by sgavil** [comment]
@bacloud14 where do you inject form's values into the new card? Can't really get it

**Comment by bacloud14** [comment]
Line 79 there I simply inject HTML which are inputs that would be links in this case.

**Comment by bacloud14** [comment]
Simply put a breakpoint on cards.js somewhere.. on line 79?

**Comment by bacloud14** [comment]
In this loop:

```
// Manipulate dom based on values from URL
keys.forEach(function (key, i) {
    try {
        if (key === "envelope") {
            form.insertAdjacentHTML('beforeend', `&nbsp;<a href="mailto:${vals[i]}">${vals[i]}</a>`)
            return
        }
        if (key === "phone") {
            form.insertAdjacentHTML('beforeend', `<br>&nbsp;<a href="tel:${vals[i]}">${vals[i]}</a><br>`)
            return
        }
        if (key === "user") {
            document.querySelectorAll('.user').forEach(node => { node.innerHTML = vals[i] })
        }
        var x = document.createElement("I");
        x.setAttribute("class", `fa fa-${key} icon`);
        form.appendChild(x)

        var y = document.createElement("INPUT");
        y.setAttribute("class", "input-field");
        y.setAttribute("value", vals[i]);
        y.setAttribute("type", "text");
        y.setAttribute("style", `background-color: ${colors[i]}`)
        y.setAttribute("readonly", "readonly");
        form.appendChild(y)

    } catch (error) {
        bugous = true
    }
})
```

Links would be like "envelope" or "phone", no need to "createElement" "INPUT" or any tag like "value" and "type".
Just add the right link (as each social website codify their user profils) and also add a little icon somehow besides the link.

**Comment by bacloud14** [comment]
Hello @sgavil 
Is this always rolling ? 
happy coding 🤟
